---
title: "test EpiNow 2 estimation"
output: pdf_document
---

See https://github.com/epiforecasts/EpiNow2


```{r}
# check the consistency of worldmet station coordiation and JHU coordinates
rm(list=ls())
library(tidyverse)
library(readr)
library(EpiNow2)
library(ggplot2)
library(dplyr)
library(lubridate)
```

```{r}
countyfiles = fs::dir_ls('counties/')
countyfiles = str_subset(countyfiles, "\\.csv") # there are 2242 files 


# metaTb = read_csv("_metaTb_1.csv")
```

```{r}
i = 20

tbCounty = readr::read_csv( countyfiles[i] )

local_cases = tbCounty[, c("date", "dailyCases")]
names( local_cases ) = c("date", "confirm")

local_cases <- local_cases %>% dplyr::filter( between(date, mdy('9/1/2020'), mdy('10/1/2020')))
local_cases$confirm[  local_cases$confirm < 0 ] = 0

#ggplot(local_cases, aes(x=date, y=confirm) ) + geom_point()
```


```{r}

for ( i in 1:2 ) {
  tbCounty = readr::read_csv( countyfiles[i] )
  
  local_cases = tbCounty[, c("date", "dailyCases")]
  names( local_cases ) = c("date", "confirm")
  
  local_cases <- local_cases %>% dplyr::filter( between(date, mdy('9/1/2020'), mdy('10/1/2020')))
  local_cases$confirm[  local_cases$confirm < 0 ] = 0
  
  reporting_delay <- bootstrapped_dist_fit(rlnorm(100, log(4), 1), max_value = 30)
  generation_time <- get_generation_time(disease = "SARS-CoV-2", source = "ganyani")
  incubation_period <- get_incubation_period(disease = "SARS-CoV-2", source = "lauer")
  
  estimates <- epinow(reported_cases = local_cases, samples=100, output='samples',
                      generation_time = generation_time,
                      delays = list(incubation_period, reporting_delay))
  
  localRtTb = estimates$estimates$summarised[ estimates$estimates$summarised$variable=='R' , all=TRUE]
  
  localRtTb2 <- localRtTb %>% select(date, mean )
  names( localRtTb2 ) = c( 'date', 'Rt' )
  
  tbCounty2 = merge( tbCounty, localRtTb2, by='date', all=TRUE)
  
  currentLocation = gsub( '\\.csv', '',  countyfiles[i] )
  outfilename = paste( currentLocation, "_v2.csv", sep='' )
  
  write_csv( tbCounty2, outfilename )
}

```
